### ISSUE TITLE
IFS incompatibilities

### ISSUE THREAD

**Issue by andychu** [oils-for-unix/oils#707]
There are a bunch of related bugs, let's catgorize them here:

- [x] #702 -- *Can't escape closing brace with backslash or single quotes in parameter expansion* -- not sure what this one is.
  - failing test cases: `spec/var-op-strip`
- [x] #291 -- *single quotes within double quoted brace sub treated differently for the # ## % %% operators* --- might be related to the above, not sure
  - failing test cases: `spec/var-sub-quote`

----

split and glob:

- [x] #698 -- `set -o noglob, echo $var` does backslash escaping when it shouldn't.  
  - this is definitely in `osh/word_eval.py`
  - failing test cases: `spec/glob`
- [ ] #627 -- *Incorrect behavior of $@ and $* when IFS='' *
  - just like no globbing, we also have problems when not splitting
  - failing test cases: `spec/word-split`
  - #331 -- smoosh also reports an empty IFS bug, not sure if it's the same
- [ ] #628 -- `IFS=':'` and `:` in literal word.  It no longer crashes, but it gives incorrect results

----

Architectural issue: #604 *consider an IR for `${}`*

**Comment by andychu** [comment]
Fixed by Koichi!
